FROM ruby:3.0.1

WORKDIR /code

COPY . /code

ENV PORT 3000

EXPOSE $PORT

#RUN apt update && \
#  apt install -y mysql-client

RUN bundle install

RUN apt-get -y install curl gnupg
RUN curl -sL https://deb.nodesource.com/setup_11.x  | bash -
RUN apt-get -y install nodejs
RUN npm install
RUN npm install --global yarn

RUN gem install rails

# Set "rails server -b 0.0.0.0" as the command to
# run when this container starts.
CMD ["rails", "server", "-b", "0.0.0.0"]
